### ISSUE TITLE
`conda mambabuild` fails with `--output-folder` flag

### ISSUE THREAD

**Issue by jph00** [mamba-org/boa#103]
When I type:

    conda mambabuild --output-folder output timm

I get the error:

```bash
Traceback (most recent call last):
  File "/home/jhoward/anaconda3/bin/conda-mambabuild", line 11, in <module>
    sys.exit(main())
  File "/home/jhoward/anaconda3/lib/python3.7/site-packages/boa/cli/mambabuild.py", line 91, in main
    variants=args["variants"],
  File "/home/jhoward/anaconda3/lib/python3.7/site-packages/conda_build/api.py", line 195, in build
    variants=variants
  File "/home/jhoward/anaconda3/lib/python3.7/site-packages/conda_build/build.py", line 3011, in build_tree
    test(pkg, config=metadata.config.copy(), stats=stats)
  File "/home/jhoward/anaconda3/lib/python3.7/site-packages/conda_build/build.py", line 2805, in test
    is_conda=metadata.name() == 'conda')
  File "/home/jhoward/anaconda3/lib/python3.7/site-packages/conda_build/environ.py", line 892, in create_env
    display_actions(actions, index)
  File "/home/jhoward/anaconda3/lib/python3.7/site-packages/conda/exports.py", line 236, in display_actions
    actions['LINK'] = [index[d] for d in actions['LINK']]
  File "/home/jhoward/anaconda3/lib/python3.7/site-packages/conda/exports.py", line 236, in <listcomp>
    actions['LINK'] = [index[d] for d in actions['LINK']]
KeyError: Dist(channel='local', dist_name='timm-0.3.2-py_0', name='timm', fmt='.tar.bz2', version='0.3.2', build_string='py_0', build_number=0, base_url=None, platform=None)
```

Using `conda build` instead works correctly.

**Comment by wolfv** [comment]
thanks, this is fixed in master. release coming today.
