### ISSUE TITLE
mambabuild: Error with index out of range

### ISSUE THREAD

**Issue by ppoilbarbe** [mamba-org/boa#140]
We build packages with mambabuild and for one package we have the error in conda_build.py: "IndexError: list index out of range".
It looks like the #88 issue but it is not cross compiling. We are on Linux and build with tox in a docker container run by gitlab-ci.
Our project is named 'octantng' so every package or channel containing octant is related to the project.
Versions (as shown in container and tox job):
- boa 0.4.2
- conda 4.9.2
- conda-build 3.21.4
- conda-package-handling 1.7.2
- conda-verify 3.4.2
- mamba 0.8.2
- tox 3.23.0
- tox-conda 0.7.1

What is strange is that sometimes it works, sometimes not. I had one package which failed and just rerunning its job with GItlab-CI was ok, but it is the same environment since, each time, it starts a new docker container with the same image (no volume mounted)

The log is:
```
py37-build run-test: commands[7] | conda config --env --set conda_build.pkg_format 2
setting PATH=/builds/octantng/programs/tox_workdir/py37-build/bin:/opt/conda/bin:/opt/conda/condabin:/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
[3149] /builds/octantng/programs/programs$ /builds/octantng/programs/tox_workdir/py37-build/bin/conda config --env --set conda_build.pkg_format 2
py37-build run-test: commands[8] | conda mambabuild --output-folder=/builds/octantng/programs/programs/build/conda_packages --override-channels --channel octantdev --channel defaults --channel conda-forge conda_recipe
setting PATH=/builds/octantng/programs/tox_workdir/py37-build/bin:/opt/conda/bin:/opt/conda/condabin:/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
[3150] /builds/octantng/programs/programs$ /builds/octantng/programs/tox_workdir/py37-build/bin/conda mambabuild --output-folder=/builds/octantng/programs/programs/build/conda_packages --override-channels --channel octantdev --channel defaults --channel conda-forge conda_recipe
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.16
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.16
Updating build index: /builds/octantng/programs/programs/build/conda_packages

Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Attempting to finalize metadata for octantng.programs
INFO:conda_build.metadata:Attempting to finalize metadata for octantng.programs
pkgs/main/linux-64       Using cache
pkgs/main/noarch         Using cache
pkgs/r/linux-64          Using cache
pkgs/r/noarch            Using cache
conda-forge/linux-64     Using cache
conda-forge/noarch       Using cache
octantdev/linux-64        
octantdev/noarch          
octant/noarch             
octant/linux-64           
conda_packages/linux-64   
conda_packages/noarch     
Transaction

  Prefix: /builds/octantng/programs/tox_workdir/py37-build

  Nothing to do

conda_packages/linux-64   
conda_packages/noarch     
Transaction

  Prefix: /builds/octantng/programs/tox_workdir/py37-build

  Updating specs:

   - pandas
   - octantng.vanilla.data
   - octantng.algo.geodesic
   - octantng.core
   - octantng.data
   - octantng.vanilla.core
   - libnetcdf=4.7.4
   - octantng.algo
   - octantng.math
   - pytest
   - marshmallow[version='>=3.2']
   - octantng.algo.grids
   - octantng.storage
   - octantng.parameters
   - xarray
   - python=3.7
   - numpy[version='>=1.18']
   - scipy
   - matplotlib
   - coverage
   - python-dateutil
   - pytest-cov
   - pip
   - packaging
   - conda-verify


  Package                               Version  Build                   Channel                                           Size
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
  Install:
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

  _libgcc_mutex                             0.1  conda_forge             conda-forge/linux-64                              3 KB
  _openmp_mutex                             4.5  1_llvm                  conda-forge/linux-64                              5 KB
  abseil-cpp                         20200923.3  h2531618_0              pkgs/main/linux-64                              919 KB
  affine                                  2.3.0  py_0                    pkgs/main/noarch                                 19 KB
  antlr-python-runtime                    4.7.2  py37hc8dfbb8_1002       conda-forge/linux-64                            165 KB
  arrow-cpp                               3.0.0  py37hf98b315_9_cpu      conda-forge/linux-64                             21 MB
  asciitree                               0.3.3  py_2                    pkgs/main/noarch                                 10 KB
  async_generator                          1.10  py37h28b3542_0          pkgs/main/linux-64                               39 KB
  atpublic                                  1.0  py_0                    conda-forge/noarch                                7 KB
  attrs                                  20.3.0  pyhd3eb1b0_0            pkgs/main/noarch                                Cached
  aws-c-common                           0.4.57  he6710b0_1              pkgs/main/linux-64                              156 KB
  aws-c-event-stream                      0.1.6  h2531618_5              pkgs/main/linux-64                               25 KB
  aws-checksums                           0.1.9  he6710b0_0              pkgs/main/linux-64                               49 KB
  aws-sdk-cpp                           1.8.151  hce553d0_0              pkgs/main/linux-64                                2 MB
  backcall                                0.2.0  pyhd3eb1b0_0            pkgs/main/noarch                                 13 KB
  backports                                 1.0  py37_1                  pkgs/main/linux-64                              Cached
  backports.functools_lru_cache           1.6.1  pyhd3eb1b0_0            pkgs/main/noarch                                Cached
  backports.tempfile                        1.0  pyhd3eb1b0_1            pkgs/main/noarch                                Cached
  backports.weakref                   1.0.post1  py37_0                  pkgs/main/linux-64                              Cached
  blas                                      1.1  openblas                conda-forge/linux-64                              1 KB
  bleach                                  3.3.0  pyhd3eb1b0_0            pkgs/main/noarch                                113 KB
  bokeh                                   2.3.0  py37h06a4308_0          pkgs/main/linux-64                                6 MB
  boost-cpp                              1.72.0  h9d3c048_4              conda-forge/linux-64                             16 MB
  brotli                                  1.0.9  he6710b0_2              pkgs/main/linux-64                              375 KB
  bzip2                                   1.0.8  h7b6447c_0              pkgs/main/linux-64                               78 KB
  c-ares                                 1.17.1  h27cfd23_0              pkgs/main/linux-64                              108 KB
  ca-certificates                     2021.1.19  h06a4308_1              pkgs/main/linux-64                              118 KB
  cairo                                  1.16.0  h7979940_1007           conda-forge/linux-64                              1 MB
  cartopy                                0.18.0  py37h26456f9_13         conda-forge/linux-64                              2 MB
  certifi                             2020.12.5  py37h06a4308_0          pkgs/main/linux-64                              141 KB
  cf-units                                2.1.4  py37h161383b_2          conda-forge/linux-64                            167 KB
  cfitsio                                 3.470  hf0d0db6_6              pkgs/main/linux-64                              814 KB
  cftime                                  1.4.1  py37h6323ea4_0          pkgs/main/linux-64                              258 KB
  click                                   7.1.2  pyhd3eb1b0_0            pkgs/main/noarch                                Cached
  click-plugins                           1.1.1  py_0                    pkgs/main/noarch                                 12 KB
  cligj                                   0.7.1  py37h06a4308_0          pkgs/main/linux-64                               13 KB
  cloudpickle                             1.6.0  py_0                    pkgs/main/noarch                                 30 KB
  conda-package-handling                  1.7.2  py37h03888b9_0          pkgs/main/linux-64                              885 KB
  conda-verify                            3.4.2  py_1                    pkgs/main/noarch                                Cached
  configparser                            5.0.2  pyhd3eb1b0_0            pkgs/main/noarch                                 22 KB
  coverage                                  5.5  py37h27cfd23_2          pkgs/main/linux-64                              254 KB
  curl                                   7.75.0  h979ede3_0              conda-forge/linux-64                            147 KB
  cycler                                 0.10.0  py37_0                  pkgs/main/linux-64                               13 KB
  cython                                0.29.22  py37h2531618_0          pkgs/main/linux-64                                2 MB
  cytoolz                                0.11.0  py37h7b6447c_0          pkgs/main/linux-64                              328 KB
  dask                                 2021.3.0  pyhd3eb1b0_0            pkgs/main/noarch                                  5 KB
  dask-core                            2021.3.0  pyhd3eb1b0_0            pkgs/main/noarch                                659 KB
  dask-jobqueue                           0.7.2  pyhd8ed1ab_1            conda-forge/noarch                               29 KB
  dateparser                              1.0.0  pyhd3eb1b0_0            pkgs/main/noarch                                153 KB
  dbus                                  1.13.18  hb2f20db_0              pkgs/main/linux-64                              504 KB
  decorator                               4.4.2  pyhd3eb1b0_0            pkgs/main/noarch                                 12 KB
  defusedxml                              0.7.1  pyhd3eb1b0_0            pkgs/main/noarch                                 23 KB
  distributed                          2021.3.0  py37h06a4308_0          pkgs/main/linux-64                                1 MB
  eccodes                                2.19.1  hea64003_0              conda-forge/linux-64                              4 MB
  entrypoints                               0.3  py37_0                  pkgs/main/linux-64                               12 KB
  expat                                  2.2.10  he6710b0_2              pkgs/main/linux-64                              153 KB
  fasteners                                0.16  pyhd3eb1b0_0            pkgs/main/noarch                                 24 KB
  fiona                                  1.8.18  py37h17d6ad9_1          conda-forge/linux-64                              1 MB
  flufl.lock                            5.0.3.1  py_0                    packages.px.cls.fr/conda/octantdev/linux-64      13 KB
  fontconfig                             2.13.1  hba837de_1004           conda-forge/linux-64                            344 KB
  freetype                               2.10.4  h5ab3b9f_0              pkgs/main/linux-64                              596 KB
  freexl                                  1.0.6  h27cfd23_0              pkgs/main/linux-64                               42 KB
  fsspec                                  0.8.7  pyhd8ed1ab_0            conda-forge/noarch                               72 KB
  future                                 0.18.2  py37_1                  pkgs/main/linux-64                              Cached
  gdal                                    3.2.1  py37hc5bc4e4_7          conda-forge/linux-64                              1 MB
  geco                           0.6.1b20201113  py37_2                  packages.px.cls.fr/conda/octantdev/linux-64       1 MB
  geopandas                               0.9.0  pyhd8ed1ab_0            conda-forge/noarch                              957 KB
  geos                                    3.9.1  h2531618_0              pkgs/main/linux-64                              973 KB
  geotiff                                 1.6.0  h11d48b3_4              conda-forge/linux-64                            278 KB
  gettext                              0.19.8.1  h9b4dc7a_1              pkgs/main/linux-64                                3 MB
  gflags                                  2.2.2  he6710b0_0              pkgs/main/linux-64                              126 KB
  giflib                                  5.2.1  h7b6447c_0              pkgs/main/linux-64                               78 KB
  glib                                   2.66.7  h9c3ff4c_1              conda-forge/linux-64                            443 KB
  glib-tools                             2.66.7  h9c3ff4c_1              conda-forge/linux-64                             85 KB
  glog                                    0.4.0  he6710b0_0              pkgs/main/linux-64                              123 KB
  grpc-cpp                               1.36.2  h7919d58_0              conda-forge/linux-64                              3 MB
  gsl                                       2.6  he838d99_2              conda-forge/linux-64                              3 MB
  gst-plugins-base                       1.18.3  h04508c2_0              conda-forge/linux-64                              2 MB
  gstreamer                              1.18.3  h3560a44_0              conda-forge/linux-64                              2 MB
  hdf4                                   4.2.13  h3ca952b_2              pkgs/main/linux-64                              714 KB
  hdf5                                   1.10.6  nompi_h7c3c948_1111     conda-forge/linux-64                              3 MB
  heapdict                                1.0.1  py_0                    pkgs/main/noarch                                  9 KB
  icu                                      68.1  h2531618_0              pkgs/main/linux-64                               12 MB
  importlib-metadata                      3.7.3  py37h89c1867_0          conda-forge/linux-64                            Cached
  importlib_metadata                      3.7.3  hd8ed1ab_0              conda-forge/noarch                              Cached
  iniconfig                               1.1.1  pyhd3eb1b0_0            pkgs/main/noarch                                  8 KB
  ipython                                7.21.0  py37hb070fc8_0          pkgs/main/linux-64                              978 KB
  ipython_genutils                        0.2.0  py37_0                  pkgs/main/linux-64                               39 KB
  jasper                                1.900.1  hd497a04_4              pkgs/main/linux-64                              198 KB
  jedi                                   0.17.2  py37h06a4308_1          pkgs/main/linux-64                              918 KB
  jinja2                                 2.11.3  pyhd3eb1b0_0            pkgs/main/noarch                                Cached
  jpeg                                       9d  h516909a_0              conda-forge/linux-64                            266 KB
  json-c                                   0.15  h98cffda_0              conda-forge/linux-64                            274 KB
  jsonschema                              3.2.0  py37_1                  pkgs/main/linux-64                              Cached
  jupyter_client                         6.1.12  pyhd8ed1ab_0            conda-forge/noarch                               79 KB
  jupyter_core                            4.7.1  py37h06a4308_0          pkgs/main/linux-64                               68 KB
  jupyterlab_pygments                     0.1.2  py_0                    pkgs/main/noarch                                  8 KB
  kealib                                 1.4.14  hcc255d8_2              conda-forge/linux-64                            186 KB
  kiwisolver                              1.3.1  py37h2531618_0          pkgs/main/linux-64                               80 KB
  krb5                                   1.17.2  h926e7f8_0              conda-forge/linux-64                              1 MB
  lcms2                                    2.12  hddcbb42_0              conda-forge/linux-64                            443 KB
  ld_impl_linux-64                       2.35.1  hea4e1c9_2              conda-forge/linux-64                            618 KB
  libaec                                  1.0.4  he6710b0_1              pkgs/main/linux-64                               32 KB
  libblas                                 3.9.0  8_openblas              conda-forge/linux-64                             11 KB
  libcblas                                3.9.0  8_openblas              conda-forge/linux-64                             11 KB
  libclang                               11.1.0  default_ha53f305_0      conda-forge/linux-64                             19 MB
  libcurl                                7.75.0  hc4aaa36_0              conda-forge/linux-64                            328 KB
  libdap4                                3.20.6  hd7c4107_1              conda-forge/linux-64                             11 MB
  libedit                          3.1.20191231  h14c3975_1              pkgs/main/linux-64                              116 KB
  libev                                    4.33  h7b6447c_0              pkgs/main/linux-64                              112 KB
  libevent                               2.1.10  hcdb4288_3              conda-forge/linux-64                              1 MB
  libffi                                    3.3  he6710b0_2              pkgs/main/linux-64                               50 KB
  libgcc-ng                               9.3.0  h2828fa1_18             conda-forge/linux-64                              8 MB
  libgdal                                 3.2.1  h38ff51b_7              conda-forge/linux-64                             13 MB
  libgfortran-ng                          7.5.0  h14aa051_18             conda-forge/linux-64                             22 KB
  libgfortran4                            7.5.0  h14aa051_18             conda-forge/linux-64                              1 MB
  libglib                                2.66.7  h3e27bee_1              conda-forge/linux-64                              3 MB
  libiconv                                 1.16  h516909a_0              conda-forge/linux-64                              1 MB
  libkml                                  1.3.0  hd79254b_1012           conda-forge/linux-64                            640 KB
  liblapack                               3.9.0  8_openblas              conda-forge/linux-64                             11 KB
  libllvm10                              10.0.1  hbcb73fb_5              pkgs/main/linux-64                               22 MB
  libllvm11                              11.1.0  hf817b99_0              conda-forge/linux-64                             29 MB
  libnetcdf                               4.7.4  nompi_h56d31a8_107      conda-forge/linux-64                              1 MB
  libnghttp2                             1.43.0  h812cca2_0              conda-forge/linux-64                            808 KB
  libopenblas                            0.3.12  pthreads_hb3c22a3_1     conda-forge/linux-64                              8 MB
  libpng                                 1.6.37  hbc83047_0              pkgs/main/linux-64                              278 KB
  libpq                                    13.1  hfd2b0eb_2              conda-forge/linux-64                              3 MB
  libprotobuf                            3.15.6  h780b84a_0              conda-forge/linux-64                              2 MB
  librttopo                               1.1.0  h1185371_6              conda-forge/linux-64                            235 KB
  libsodium                              1.0.18  h7b6447c_0              pkgs/main/linux-64                              244 KB
  libspatialindex                         1.9.3  he6710b0_0              pkgs/main/linux-64                                2 MB
  libspatialite                           5.0.1  he52d314_3              conda-forge/linux-64                              4 MB
  libssh2                                 1.9.0  h1ba5d50_1              pkgs/main/linux-64                              269 KB
  libstdcxx-ng                            9.3.0  h6de172a_18             conda-forge/linux-64                              4 MB
  libthrift                              0.14.1  he6d91bd_1              conda-forge/linux-64                              5 MB
  libtiff                                 4.2.0  hdc55705_0              conda-forge/linux-64                            633 KB
  libutf8proc                             2.6.1  h27cfd23_0              pkgs/main/linux-64                               80 KB
  libuuid                                2.32.1  h14c3975_1000           conda-forge/linux-64                             26 KB
  libwebp-base                            1.2.0  h27cfd23_0              pkgs/main/linux-64                              437 KB
  libxcb                                   1.14  h7b6447c_0              pkgs/main/linux-64                              505 KB
  libxkbcommon                            1.0.3  he3ba5ed_0              conda-forge/linux-64                            581 KB
  libxml2                                2.9.10  h72842e0_3              conda-forge/linux-64                              1 MB
  llvm-openmp                            11.0.1  h4bd325d_0              conda-forge/linux-64                              5 MB
  llvmlite                               0.36.0  py37h9d7f4d0_0          conda-forge/linux-64                              3 MB
  locket                                  0.2.1  py37h06a4308_1          pkgs/main/linux-64                               10 KB
  lz4-c                                   1.9.3  h2531618_0              pkgs/main/linux-64                              186 KB
  markupsafe                              1.1.1  py37h14c3975_1          pkgs/main/linux-64                              Cached
  marshmallow                            3.10.0  pyhd3eb1b0_0            pkgs/main/noarch                                 82 KB
  matplotlib                              3.3.4  py37h06a4308_0          pkgs/main/linux-64                               26 KB
  matplotlib-base                         3.3.4  py37h62a2d02_0          pkgs/main/linux-64                                5 MB
  mistune                                 0.8.4  py37h14c3975_1001       pkgs/main/linux-64                               54 KB
  mkl                                    2020.4  h726a3e6_304            conda-forge/linux-64                            216 MB
  monotonic                                 1.5  py_0                    pkgs/main/noarch                                 17 KB
  more-itertools                          8.7.0  pyhd3eb1b0_0            pkgs/main/noarch                                 42 KB
  msgpack-python                          1.0.2  py37hff7bd54_1          pkgs/main/linux-64                               81 KB
  munch                                   2.5.0  py_0                    pkgs/main/noarch                                 15 KB
  mysql-common                           8.0.23  ha770c72_1              conda-forge/linux-64                              2 MB
  mysql-libs                             8.0.23  h935591d_1              conda-forge/linux-64                              2 MB
  nbclient                                0.5.3  pyhd3eb1b0_0            pkgs/main/noarch                                 62 KB
  nbconvert                               6.0.7  py37_0                  pkgs/main/linux-64                              484 KB
  nbformat                                5.1.2  pyhd3eb1b0_1            pkgs/main/noarch                                 68 KB
  ncurses                                   6.2  he6710b0_1              pkgs/main/linux-64                              817 KB
  nest-asyncio                            1.5.1  pyhd3eb1b0_0            pkgs/main/noarch                                 10 KB
  netcdf4                                 1.5.6  nompi_py37hdbee05a_100  conda-forge/linux-64                            529 KB
  nspr                                     4.29  he1b5a44_1              conda-forge/linux-64                            232 KB
  nss                                      3.62  hb5efdd6_0              conda-forge/linux-64                              2 MB
  numba                                  0.53.0  py37h7dd73a4_0          conda-forge/linux-64                              4 MB
  numba-scipy                             0.2.0  py_1                    conda-forge/noarch                               10 KB
  numcodecs                               0.7.3  py37h2531618_0          pkgs/main/linux-64                              620 KB
  numpy                                  1.20.1  py37haa41c4c_0          conda-forge/linux-64                              6 MB
  octantng.algo                        0.15.0b0  py37hfeaa757_326        packages.px.cls.fr/conda/octantdev/linux-64      90 KB
  octantng.algo.geodesic               0.13.0b0  py37hfeaa757_412        packages.px.cls.fr/conda/octantdev/linux-64     188 KB
  octantng.algo.grids                  0.16.0b0  py37hfeaa757_431        packages.px.cls.fr/conda/octantdev/linux-64      87 KB
  octantng.core                        0.21.0b0  py37hfeaa757_290        packages.px.cls.fr/conda/octantdev/linux-64      73 KB
  octantng.data                         0.5.0b0  py37hfeaa757_86         packages.px.cls.fr/conda/octantdev/linux-64     111 KB
  octantng.math                        0.16.0b0  py37hfeaa757_231        packages.px.cls.fr/conda/octantdev/linux-64      40 KB
  octantng.parameters                  0.21.0b0  py37hfeaa757_241        packages.px.cls.fr/conda/octantdev/linux-64     103 KB
  octantng.storage                     0.14.0b0  py37hfeaa757_346        packages.px.cls.fr/conda/octantdev/linux-64     101 KB
  octantng.vanilla.core                0.15.0b0  py37_122                packages.px.cls.fr/conda/octantdev/linux-64      21 KB
  octantng.vanilla.data                0.13.0b0  py37hfeaa757_201        packages.px.cls.fr/conda/octantdev/linux-64     791 KB
  olefile                                  0.46  py37_0                  pkgs/main/linux-64                               50 KB
  openblas                               0.3.12  pthreads_h43bd3aa_1     conda-forge/linux-64                              9 MB
  openjpeg                                2.4.0  hf7af979_0              conda-forge/linux-64                            525 KB
  openssl                                1.1.1j  h27cfd23_0              pkgs/main/linux-64                                3 MB
  orc                                     1.6.7  heec2584_1              conda-forge/linux-64                            750 KB
  packaging                                20.9  pyhd3eb1b0_0            pkgs/main/noarch                                 37 KB
  pandas                                  1.2.3  py37ha9443f7_0          pkgs/main/linux-64                                9 MB
  pandoc                                   2.12  h7f98852_0              conda-forge/linux-64                             12 MB
  pandocfilters                           1.4.3  py37h06a4308_1          pkgs/main/linux-64                               14 KB
  parso                                   0.7.1  pyh9f0ad1d_0            conda-forge/noarch                               70 KB
  partd                                   1.1.0  py_0                    pkgs/main/noarch                                 20 KB
  pcre                                     8.44  he6710b0_0              pkgs/main/linux-64                              212 KB
  pexpect                                 4.8.0  py37_1                  pkgs/main/linux-64                               77 KB
  pickleshare                             0.7.5  py37_1001               pkgs/main/linux-64                               13 KB
  pillow                                  8.1.2  py37he98fc37_0          pkgs/main/linux-64                              624 KB
  pip                                    21.0.1  py37h06a4308_0          pkgs/main/linux-64                                2 MB
  pixman                                 0.40.0  h7b6447c_0              pkgs/main/linux-64                              370 KB
  pluggy                                 0.13.1  py37_0                  pkgs/main/linux-64                               33 KB
  poppler                                0.89.0  h2de54a5_5              conda-forge/linux-64                             16 MB
  poppler-data                           0.4.10  h06a4308_0              pkgs/main/linux-64                                2 MB
  postgresql                               13.1  h6303168_2              conda-forge/linux-64                              5 MB
  proj                                    7.2.0  h277dcde_2              conda-forge/linux-64                              3 MB
  prompt-toolkit                         3.0.17  pyha770c72_0            conda-forge/noarch                              Cached
  psutil                                  5.8.0  py37h27cfd23_1          pkgs/main/linux-64                              Cached
  ptyprocess                              0.7.0  pyhd3eb1b0_2            pkgs/main/noarch                                 17 KB
  py                                     1.10.0  pyhd3eb1b0_0            pkgs/main/noarch                                 76 KB
  pyarrow                                 3.0.0  py37he0739d4_3          pkgs/main/linux-64                                2 MB
  pybind11                                2.6.2  py37h2527ec5_0          conda-forge/linux-64                            148 KB
  pybind11-global                         2.6.2  py37h2527ec5_0          conda-forge/linux-64                            181 KB
  pyfes                                   2.9.2  py37h6bb024c_1          packages.px.cls.fr/conda/octantdev/linux-64     456 KB
  pygments                                2.8.1  pyhd3eb1b0_0            pkgs/main/noarch                                Cached
  pygsl                                 2.3.0.1  py37_5                  packages.px.cls.fr/conda/octantdev/linux-64     979 KB
  pyparsing                               2.4.7  pyhd3eb1b0_0            pkgs/main/noarch                                 59 KB
  pyproj                                  3.0.1  py37h63c117d_0          conda-forge/linux-64                            475 KB
  pyqt                                   5.12.3  py37h89c1867_7          conda-forge/linux-64                             21 KB
  pyqt-impl                              5.12.3  py37he336c9b_7          conda-forge/linux-64                              6 MB
  pyqt5-sip                             4.19.18  py37hcd2ae1e_7          conda-forge/linux-64                            310 KB
  pyqtchart                                5.12  py37he336c9b_7          conda-forge/linux-64                            256 KB
  pyqtwebengine                          5.12.1  py37he336c9b_7          conda-forge/linux-64                            175 KB
  pyrsistent                             0.17.3  py37h7b6447c_0          pkgs/main/linux-64                              Cached
  pyshp                                   2.1.3  pyhd3eb1b0_0            pkgs/main/noarch                                 37 KB
  pytest                                  6.2.2  py37h06a4308_2          pkgs/main/linux-64                              439 KB
  pytest-cov                             2.11.1  pyhd3eb1b0_0            pkgs/main/noarch                                 21 KB
  pytest-runner                           5.3.0  pyhd3eb1b0_0            pkgs/main/noarch                                 11 KB
  python                                 3.7.10  hdb3f193_0              pkgs/main/linux-64                               45 MB
  python-dateutil                         2.8.1  pyhd3eb1b0_0            pkgs/main/noarch                                221 KB
  python_abi                                3.7  1_cp37m                 conda-forge/linux-64                              4 KB
  pytz                                   2021.1  pyhd3eb1b0_0            pkgs/main/noarch                                Cached
  pyyaml                                  5.4.1  py37h27cfd23_1          pkgs/main/linux-64                              Cached
  pyzmq                                  22.0.3  py37h336d617_1          conda-forge/linux-64                            524 KB
  qt                                     5.12.9  hda022c4_4              conda-forge/linux-64                            100 MB
  rasterio                                1.2.1  py37hb284c01_2          conda-forge/linux-64                              8 MB
  re2                                2020.11.01  h2531618_1              pkgs/main/linux-64                              315 KB
  readline                                  8.1  h27cfd23_0              pkgs/main/linux-64                              362 KB
  regex                              2020.11.13  py37h27cfd23_0          pkgs/main/linux-64                              319 KB
  rtree                                   0.9.7  py37h0b55af0_1          conda-forge/linux-64                             45 KB
  scipy                                   1.6.1  py37hf56f3a7_0          pkgs/main/linux-64                               15 MB
  setuptools                             52.0.0  py37h06a4308_0          pkgs/main/linux-64                              710 KB
  shapely                                 1.7.1  py37hf7ed6d2_4          conda-forge/linux-64                            450 KB
  six                                    1.15.0  py37h06a4308_0          pkgs/main/linux-64                               27 KB
  snappy                                  1.1.8  he6710b0_0              pkgs/main/linux-64                               40 KB
  snuggs                                  1.4.7  py_0                    pkgs/main/noarch                                 11 KB
  sortedcontainers                        2.3.0  pyhd3eb1b0_0            pkgs/main/noarch                                 26 KB
  sqlite                                 3.34.0  h74cdb3f_0              conda-forge/linux-64                              1 MB
  tatsu                                   4.4.0  py37hc8dfbb8_2          conda-forge/linux-64                            141 KB
  tblib                                   1.7.0  py_0                    pkgs/main/noarch                                 16 KB
  testpath                                0.4.4  pyhd3eb1b0_0            pkgs/main/noarch                                 85 KB
  tiledb                                  2.2.4  hb9a9e87_2              conda-forge/linux-64                              3 MB
  tk                                     8.6.10  hbc83047_0              pkgs/main/linux-64                                3 MB
  toml                                   0.10.2  pyhd8ed1ab_0            conda-forge/noarch                               18 KB
  toolz                                  0.11.1  pyhd3eb1b0_0            pkgs/main/noarch                                 46 KB
  tornado                                   6.1  py37h27cfd23_0          pkgs/main/linux-64                              589 KB
  tqdm                                   4.59.0  pyhd8ed1ab_0            conda-forge/noarch                               77 KB
  traitlets                               5.0.5  pyhd3eb1b0_0            pkgs/main/noarch                                 81 KB
  typing_extensions                     3.7.4.3  pyha847dfd_0            pkgs/main/noarch                                Cached
  tzcode                                  2021a  h7f98852_1              conda-forge/linux-64                             68 KB
  tzdata                                  2021a  he74cb21_0              conda-forge/noarch                              121 KB
  tzlocal                                   2.1  py37_0                  pkgs/main/linux-64                               29 KB
  udunits2                            2.2.27.27  h360fe7b_0              conda-forge/linux-64                            161 KB
  wcwidth                                 0.2.5  py_0                    pkgs/main/noarch                                Cached
  webencodings                            0.5.1  py37_1                  pkgs/main/linux-64                               19 KB
  wheel                                  0.36.2  pyhd3eb1b0_0            pkgs/main/noarch                                 33 KB
  xarray                                 0.17.0  pyhd3eb1b0_0            pkgs/main/noarch                                510 KB
  xerces-c                                3.2.3  h9d8b166_2              conda-forge/linux-64                              2 MB
  xorg-kbproto                            1.0.7  h14c3975_1002           conda-forge/linux-64                             26 KB
  xorg-libice                            1.0.10  h516909a_0              conda-forge/linux-64                             57 KB
  xorg-libsm                              1.2.3  hd9c2040_1000           conda-forge/linux-64                             26 KB
  xorg-libx11                             1.7.0  h36c2ea0_0              conda-forge/linux-64                            943 KB
  xorg-libxext                            1.3.4  h7f98852_1              conda-forge/linux-64                             54 KB
  xorg-libxrender                        0.9.10  h7f98852_1003           conda-forge/linux-64                             32 KB
  xorg-renderproto                       0.11.1  h14c3975_1002           conda-forge/linux-64                              8 KB
  xorg-xextproto                          7.3.0  h14c3975_1002           conda-forge/linux-64                             27 KB
  xorg-xproto                            7.0.31  h27cfd23_1007           pkgs/main/linux-64                               73 KB
  xz                                      5.2.5  h7b6447c_0              pkgs/main/linux-64                              341 KB
  yaml                                    0.2.5  h7b6447c_0              pkgs/main/linux-64                               75 KB
  zarr                                    2.6.1  pyhd3eb1b0_0            pkgs/main/noarch                                101 KB
  zeromq                                  4.3.4  h9c3ff4c_0              conda-forge/linux-64                            352 KB
  zict                                    2.0.0  pyhd3eb1b0_0            pkgs/main/noarch                                 10 KB
  zipp                                    3.4.1  pyhd8ed1ab_0            conda-forge/noarch                              Cached
  zlib                                   1.2.11  h7b6447c_3              pkgs/main/linux-64                              103 KB
  zstd                                    1.4.9  ha95c52a_0              conda-forge/linux-64                            431 KB

  Summary:

  Install: 281 packages

  Total download: 757 MB

─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Traceback (most recent call last):
  File "/builds/octantng/programs/tox_workdir/py37-build/bin/conda-mambabuild", line 11, in <module>
    sys.exit(main())
  File "/builds/octantng/programs/tox_workdir/py37-build/lib/python3.7/site-packages/boa/cli/mambabuild.py", line 140, in main
    call_conda_build(action, config)
  File "/builds/octantng/programs/tox_workdir/py37-build/lib/python3.7/site-packages/boa/cli/mambabuild.py", line 125, in call_conda_build
    **kwargs,
  File "/builds/octantng/programs/tox_workdir/py37-build/lib/python3.7/site-packages/conda_build/api.py", line 195, in build
    variants=variants
  File "/builds/octantng/programs/tox_workdir/py37-build/lib/python3.7/site-packages/conda_build/build.py", line 3073, in build_tree
    notest=notest,
  File "/builds/octantng/programs/tox_workdir/py37-build/lib/python3.7/site-packages/conda_build/build.py", line 2031, in build
    output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
  File "/builds/octantng/programs/tox_workdir/py37-build/lib/python3.7/site-packages/conda_build/render.py", line 789, in expand_outputs
    for (output_dict, m) in deepcopy(_m).get_output_metadata_set(permit_unsatisfiable_variants=False):
  File "/builds/octantng/programs/tox_workdir/py37-build/lib/python3.7/site-packages/conda_build/metadata.py", line 2117, in get_output_metadata_set
    bypass_env_check=bypass_env_check)
  File "/builds/octantng/programs/tox_workdir/py37-build/lib/python3.7/site-packages/conda_build/metadata.py", line 777, in finalize_outputs_pass
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/builds/octantng/programs/tox_workdir/py37-build/lib/python3.7/site-packages/conda_build/render.py", line 549, in finalize_metadata
    exclude_pattern)
  File "/builds/octantng/programs/tox_workdir/py37-build/lib/python3.7/site-packages/conda_build/render.py", line 410, in add_upstream_pins
    permit_unsatisfiable_variants, exclude_pattern)
  File "/builds/octantng/programs/tox_workdir/py37-build/lib/python3.7/site-packages/conda_build/render.py", line 379, in _read_upstream_pin_files
    extra_run_specs = get_upstream_pins(m, actions, env)
  File "/builds/octantng/programs/tox_workdir/py37-build/lib/python3.7/site-packages/conda_build/render.py", line 365, in get_upstream_pins
    loc, dist = execute_download_actions(m, actions, env=env, package_subset=pkg)[pkg]
  File "/builds/octantng/programs/tox_workdir/py37-build/lib/python3.7/site-packages/conda_build/render.py", line 322, in execute_download_actions
    pkg_record = [_ for _ in index if _.dist_name == pkg_dist][0]
IndexError: list index out of range
```

**Comment by FHTMitchell** [comment]
Seeing the same issue with `boa=0.6.0` and `mamba=0.15.0` on linux (no cross compiling). Seems to happen every time for `mambabuild` in my case.

**Comment by wolfv** [comment]
@FHTMitchell do you have some reproducer?

**Comment by wolfv** [comment]
ping @FHTMitchell a reproducer of some sort would be really helpful!

**Comment by ppoilbarbe** [comment]
I tried to find a simple way to reproduce it, but I did not find.
But as for @FHTMitchell, with these constraints "mamba>=0.13.0,<0.15.0, boa<0.6.1" I don't (yet) have the problem.
With boa=0.6.1 the problem occurs (using mambabuild) but not in all cases. As we have very big projects with many dependencies, I did not find how to extract an working example.
But I pached the source of conda to show the content of pkg_dist and all asked variables and what is said to be missing was here.
