### ISSUE TITLE
Handle missing repodata.json

### ISSUE THREAD

**Issue by phausamann** [mamba-org/boa#22]
`conda build purge-all` removes various folders, including `conda-bld/noarch` which leads to this error in `conda mambabuild`:

```
Traceback (most recent call last):
  File "/home/peter/miniconda3/bin/conda-mambabuild", line 8, in <module>
    sys.exit(main())
  File "/home/peter/miniconda3/lib/python3.7/site-packages/boa/cli/mambabuild.py", line 278, in main
    solver.replace_channels()
  File "/home/peter/miniconda3/lib/python3.7/site-packages/boa/cli/mambabuild.py", line 149, in replace_channels
    self.local_index = get_index(("local",), platform=self.platform, prepend=False)
  File "/home/peter/miniconda3/lib/python3.7/site-packages/boa/cli/mambabuild.py", line 111, in get_index
    is_downloaded = dlist.download(True)
RuntimeError: Download error (37) Couldn't read a file:// file [file:///home/peter/miniconda3/conda-bld/noarch/repodata.json]
```

**Comment by saraedum** [comment]
Just writing a `{}` to repodata.json seems to be a workaround for me.

**Comment by sanzoghenzo** [comment]
I'm having the same issue on 0.3.0 if I use the `--output-folder` option.

Running `conda mambabuild conda --no-test --output-folder build` raises the mentioned exception.

running without `--output-folder` works fine, and subsequent calls works also with it.
