### ISSUE TITLE
Getting Started Noob Questions

### ISSUE THREAD

**Issue by vsoch** [mamba-org/boa#281]
heyo! I'm following the README to test things out, basically I want what would be considered a "getting started" set of steps, and I am a good test user for this because I'm not totally familiar with the details of mamba. So first I tried cloning and installing:

```bash
git clone https://github.com/mamba-org/boa
cd boa
python -m venv env
source env/bin/activate
pip install -e .
```
And then I wanted to follow the build example in the readme:

```bash
cd tests/recipes
```
```bash
$ boa build jedi
Traceback (most recent call last):
  File "/home/vanessa/Desktop/Code/boa/env/bin/boa", line 33, in <module>
    sys.exit(load_entry_point('boa', 'console_scripts', 'boa')())
  File "/home/vanessa/Desktop/Code/boa/env/bin/boa", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/vanessa/anaconda3/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/home/vanessa/anaconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/vanessa/Desktop/Code/boa/boa/cli/boa.py", line 9, in <module>
    from mamba.utils import init_api_context
ModuleNotFoundError: No module named 'mamba.utils'
```
Then I found [the docs here](https://boa-build.readthedocs.io/en/latest/getting_started.html) and realized I might be following the wrong thing, so I did:

```bash
$ conda install boa -c conda-forge
```
and that worked to install boa (so maybe the README should just point to that content). But then I tried build and I'm not sure what happened?

```bash
$ boa build jedi

           _
          | |__   ___   __ _
          | '_ \ / _ \ / _` |
          | |_) | (_) | (_| |
          |_.__/ \___/ \__,_|


Loading config files: 

Updating build index: /home/vanessa/anaconda3/conda-bld

[]

Assembling all recipes and variants
```
Sorry for the noob questions - trying to get my head around this new tool. Thank you!

**Comment by wolfv** [comment]
Hey, to build the jedi recipe (if you have it) you probably should point to the directory containing the `recipe.yaml` file.
You could try the `test/recipes-v2/grayskull` recipe, for example.

We also have a couple more boa-ified recipes here: https://github.com/mamba-org/boa-forge – these are a bit hacky, though (especially because of the `static` feature which lead to changing the names of all packages & dependencies to xxx-static, which I want to do automatically in the future). 

I think the `libarchive` recipe can give a decent idea of what I think "features" could look like: https://github.com/mamba-org/boa-forge/blob/master/libarchive/recipe.yaml

Sorry for the bad README :)
