### ISSUE TITLE
Convert complains of duplicate keys in some recipes

### ISSUE THREAD

**Issue by bamarco** [mamba-org/boa#385]
```
Traceback (most recent call last):
  File "/home/monkey/micromamba/envs/boa-dev/bin/boa", line 33, in <module>
    sys.exit(load_entry_point('boa', 'console_scripts', 'boa')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/monkey/proj/lib/boa/boa/cli/boa.py", line 223, in main
    convert.main(args.target)
  File "/home/monkey/proj/lib/boa/boa/cli/convert.py", line 132, in main
    yaml.load("".join(rest_lines))
  File "/home/monkey/micromamba/envs/boa-dev/lib/python3.11/site-packages/ruamel/yaml/main.py", line 451, in load
    return constructor.get_single_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/monkey/micromamba/envs/boa-dev/lib/python3.11/site-packages/ruamel/yaml/constructor.py", line 114, in get_single_data
    return self.construct_document(node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/monkey/micromamba/envs/boa-dev/lib/python3.11/site-packages/ruamel/yaml/constructor.py", line 123, in construct_document
    for _dummy in generator:
  File "/home/monkey/micromamba/envs/boa-dev/lib/python3.11/site-packages/ruamel/yaml/constructor.py", line 1470, in construct_yaml_map
    self.construct_mapping(node, data, deep=True)
  File "/home/monkey/micromamba/envs/boa-dev/lib/python3.11/site-packages/ruamel/yaml/constructor.py", line 1359, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/monkey/micromamba/envs/boa-dev/lib/python3.11/site-packages/ruamel/yaml/constructor.py", line 145, in construct_object
    data = self.construct_non_recursive_object(node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/monkey/micromamba/envs/boa-dev/lib/python3.11/site-packages/ruamel/yaml/constructor.py", line 186, in construct_non_recursive_object
    for _dummy in generator:
  File "/home/monkey/micromamba/envs/boa-dev/lib/python3.11/site-packages/ruamel/yaml/constructor.py", line 1470, in construct_yaml_map
    self.construct_mapping(node, data, deep=True)
  File "/home/monkey/micromamba/envs/boa-dev/lib/python3.11/site-packages/ruamel/yaml/constructor.py", line 1360, in construct_mapping
    if self.check_mapping_key(node, key_node, maptyp, key, value):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/monkey/micromamba/envs/boa-dev/lib/python3.11/site-packages/ruamel/yaml/constructor.py", line 276, in check_mapping_key
    raise DuplicateKeyError(*args)
ruamel.yaml.constructor.DuplicateKeyError: while constructing a mapping
  in "<unicode string>", line 7, column 3:
      url: 'https://github.com/stan-de ... 
      ^ (line: 7)
found duplicate key "url" with value "https://github.com/stan-dev/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}-linux-arm64.tar.gz  # [aarch64]" (original value: "https://github.com/stan-dev/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz  # [x86 or arm64]")
  in "<unicode string>", line 9, column 3:
      url: 'https://github.com/stan-de ... 
      ^ (line: 9)

To suppress this check see:
    http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys
```

**Comment by bamarco** [comment]
I can work on fixing this, I'm just unsure of the desired behaviour. Does conda-forge do something to deduplicate these keys before yaml processing? What does boa need for a well-formed recipe?

The use case is when there are multiple architecture urls with sha256 hashes.

**Comment by bamarco** [comment]
Found the desired result in the boa spec:
```
  source:
    - url: https://package1.com/a.tar.bz2
      folder: stuff
    - url: https://package1.com/b.tar.bz2
      folder: stuff
    - git_url: https://github.com/mamba-org/boa
      folder: boa
```

**Comment by bamarco** [comment]
actually in this case it would be
```
source:
  - sel(not win):
      url: http://path/to/unix/source
  - sel(win):
      url: http://path/to/windows/source
```
