### ISSUE TITLE
missing repodata.json when using --output-folder on clean build directory

### ISSUE THREAD

**Issue by sanzoghenzo** [mamba-org/boa#97]
I found out that the error I have is not the same as #22 , it is triggered later on in the code execution.

Running conda `mambabuild conda --output-folder build` on a fresh boa installation or after `conda build purge-all` raises the following:

```
Traceback (most recent call last):
  File "/opt/conda/bin/conda-mambabuild", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.7/site-packages/boa/cli/mambabuild.py", line 91, in main
    variants=args["variants"],
  File "/opt/conda/lib/python3.7/site-packages/conda_build/api.py", line 195, in build
    variants=variants
  File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 3013, in build_tree
    notest=notest,
  File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 2048, in build
    create_build_envs(top_level_pkg, notest)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 1896, in create_build_envs
    channel_urls=tuple(m.config.channel_urls))
  File "/opt/conda/lib/python3.7/site-packages/boa/cli/mambabuild.py", line 52, in mamba_get_install_actions
    solver.replace_channels()
  File "/opt/conda/lib/python3.7/site-packages/boa/core/solver.py", line 98, in replace_channels
    self.local_index = get_index(("local",), platform=self.platform, prepend=False)
  File "/opt/conda/lib/python3.7/site-packages/mamba/utils.py", line 74, in get_index
    is_downloaded = dlist.download(True)
RuntimeError: Download error (37) Couldn't read a file:// file [file:///opt/conda/conda-bld/noarch/repodata.json]
```

running without `--output-folder` works fine, and subsequent calls works also with it.

**Comment by buckettt** [comment]
Same issue here when referencing the channel in an environment.yml

@sanzoghenzo any progress?

**Comment by wolfv** [comment]
we call `conda index` in a couple of places. Maybe we just need to add another call somewhere or change some arguments? 
PR's welcome!
